### PR TITLE
fix encoding and add session param

### PR DESCRIPTION
**Pull request by Weidows**

### CODE REVIEW

**Comment by joaojacome** [comment]
Hello!

The bw session can be reused by passing the `BW_SESSION` environment variable. Wouldn't that cover this?

**Comment by Weidows** [comment]
hello!
env `BW_SESSION` works well, but I think it's also a good way to pass session key by parameter like bw official cli
cause setting environment variables in windows is a little tricky

**Review by joshuaauger — COMMENTED** [review]
This looks like a worthy addition.

**Comment by joaojacome** [comment]
Merged. Thanks for the contribution :)

**Pull request merged**
