### PR TITLE
Improved documentation, changed link to archived Bitwarden CLI

### PR DESCRIPTION
**Pull request by cargocultprogramming**
Just expanding a bit on the documentation for users that might need a bit more context on how to get this up and running.

Also the link to the Bitwarden CLI github repo points to an archived project. I changed that to the official Bitwarden download page and added a separate pointer to the current instructions on how to build the CLI from github sources.

Hope that helps!

### CODE REVIEW

**Comment by joaojacome** [comment]
Thanks for the contribution. I'll merge it later today.

**Comment by cargocultprogramming** [comment]
Nudge.

Also [issue 35](https://github.com/joaojacome/bitwarden-ssh-agent/issues/35) is still open, can send a PR if you prefer.

**Comment by cargocultprogramming** [comment]
Added the ability to specify key lifetime leveraging `ssh-add -t`. This addresses part of the discussion in PR #32 - in particular the feature to remove keys from sshd. My proposal allows setting a maximum time for keys to stay in memory, without big changes or additional libraries.

**Comment by cargocultprogramming** [comment]
Moved the agent-lifetime code to a different branch and will submit another PR with that.

This branch now contains 2 changes:

1.  Documentation update
2. subprocess check parameter set to False - see my issue report #35 

Let me know if you also want number 2 from above separated out.

**Pull request closed without merging**
