### PR TITLE
Refactor to run within a single Python script

### PR DESCRIPTION
**Pull request by scottwallacesh**
I liked your project but decided to make some changes to remove the need for the shell script.  I then performed a few more changes and have ended up with nearly a complete rewrite.

I hope this is okay.

### CODE REVIEW

**Comment by joaojacome** [comment]
Hey, thanks for your contribution :)

Looks (almost) fine for me, although I had some issues regarding the `--nointeraction` flag sent in some commands. I couldn't find it documented anywhere, although I could find it in bw source code.

Maybe we should add a version check?

Thanks again, it looks really good!

**Comment by scottwallacesh** [comment]
Looks like [it was added in v1.9.0](https://github.com/bitwarden/cli/commit/e7450d27e468f0e68fe5b75f9c52ffa952185484).

**Comment by scottwallacesh** [comment]
I've updated the code to check the version and only add the `--nointeraction` argument if it's supported.  I've made it extensible so it can be used to check for compatibility in the future, should it be required.

**Comment by joaojacome** [comment]
Sorry for the delay on reviewing this, it's merged now.

Thank you very much for this contribution :)

**Pull request merged**
